### ISSUE TITLE
Thanks for making this mod, could you explain a little more what's different between this and EM?

### ISSUE THREAD

**Issue by EpsilonCommunity** [SceptreOfficial/Enhanced-Movement-Rework#1]
Thanks for making this mod, could you explain a little more what's different between this and EM?

**Comment by SceptreOfficial** [comment]
The goal of the mod was to simply the functions and get rid of the issues EM was causing. Mainly the walking surface it spawns under players that could mess with ACE fastroping, sitting, and potentially AI helo landing.
The code base is also open source so improvements to make it faster and better are always welcome.

**Comment by SceptreOfficial** [comment]
Closing this issue since question was answered. If you have more questions, reopen this issue.

**Comment by EpsilonCommunity** [comment]
Thank you. We'd noticed the ACE issues too. However we didn't pinpoint it towards EM. :)
Hopefully this will help us out! Thanks again.
