### ISSUE TITLE
Issues with current ACE Stamina handling

### ISSUE THREAD

**Issue by Freddo3000** [SceptreOfficial/Enhanced-Movement-Rework#10]
Unfortunately applying a stamina modifier for a duration after climbing objects isn't really sufficient, and often times outright doesn't work. As the modifier is only applied for a couple of seconds, it might not get caught in a stamina script cycle, and also if you simply stand still for a couple of seconds after climbing or jumping you can entirely negate it.

This can be fixed as in https://github.com/SceptreOfficial/Enhanced-Movement-Rework/blob/master/addons/main/functions/fnc_getStamina.sqf by instead changing the `ace_advanced_fatigue_anReserve` variable instead of applying a duty factor.

**Comment by SceptreOfficial** [comment]
If you want to make a pull request to solve this issue, feel free. Diwako gave me those stamina functions. Idk how ACE stamina works so I would have to figure out how it works before I go about breaking it.

**Comment by SceptreOfficial** [comment]
Fixed with: 72a4925cee80b27a6ca0f6ebc42f7e599f9b0f83
