### ISSUE TITLE
Add option for slowing animation speeds 

### ISSUE THREAD

**Issue by Freddo3000** [SceptreOfficial/Enhanced-Movement-Rework#11]
Can probably be done through [`setAnimSpeedCoef`](https://community.bistudio.com/wiki/setAnimSpeedCoef), but it is probably easier said than done.

**Comment by SceptreOfficial** [comment]
I was messing with this before but some scripts (ACE stamina specifically) are constantly modifying this and rendered it useless in my testing. I think this just needs a complete compatibility patch to handle all of the ACE stamina stuff. I probably won't get around to it for a little while, though.

**Comment by SceptreOfficial** [comment]
Implemented with: 72a4925cee80b27a6ca0f6ebc42f7e599f9b0f83
