### ISSUE TITLE
Feature Request: Customization Options

### ISSUE THREAD

**Issue by G3rrus** [SceptreOfficial/Enhanced-Movement-Rework#2]
Is it completely out of scope or would it be possible to ever see some addon options for this. Mainly to allow some fine tuning depending on how a community liked to play? I'm thinking of maybe a toggle to allow/disallow jumping and settings for max climb height and maximum weight for different heights. As an example it could look at little like this:

https://cdn.discordapp.com/attachments/447805538118664202/693856457791111218/unknown.png
![grafik](https://user-images.githubusercontent.com/18622487/77854593-68ef7c00-71eb-11ea-8286-91b13d3f4719.png)

**Comment by SceptreOfficial** [comment]
Yeah, addon options will be added eventually. These are a good set to reference. Are these from diwako's or dedmen's versions by chance? Also, can you elaborate on the weight settings?

**Comment by G3rrus** [comment]
Yeah diwakos. Basically the weight category puts max limit on the amount of weight in pounds up until you are considered to carry too much to still perform said action.

**Comment by diwako** [comment]
Weight settings are in pound in this one, as that was easier to work with and comes around as round number. Turns out arma's mass system is kind of in pound as well, somewhat.

In KG it would be around `45.359702440351991290937131452418`. So yeah, you get the idea.

**Comment by SceptreOfficial** [comment]
CBA settings have been implemented.
See: https://github.com/SceptreOfficial/Enhanced-Movement-Rework/blob/master/addons/main/XEH_preInit.sqf#L9-L115

Closing this issue.
