### ISSUE TITLE
Players are getting Telported when using EM

### ISSUE THREAD

**Issue by Nilia119** [SceptreOfficial/Enhanced-Movement-Rework#20]
Hi, we are using this mod in my Unit and ther allways was a quite annoying Bug. We use it since ca. May this year and right after we incorporated it in our Modpack, Zeus's started almost right away to complain about players getting teleported to the lower left corner of the Map.
After i did some testing, it seemed clear, what the problem was or more precisely what is causing it and kinda how to "prevent" it.
If you add Objekts via ZEN or Achilles to Zeus, you add some invisible arrows around the players, if you use the Module in their proximity. If you remove/delete them, the Player is "fucked" and can't climb anymore insted he gets Teleported. 
Sometimes there are arrows attached to Objekts, where a player previously had climbed. And if you are not VERY carefull while adding/deleting stuff, you "fuck" the corresponding player, since you cannot undo/debug that function.
We do mostly Zeus Missions with 30+ Players and it is sometimes hard to keep track of those little arrows and they occasionally get removed.
I would really appreciate, if you could fix that.
If you need additional Informations, i can provide them.
Have a nice day!

**Comment by Nilia119** [comment]
To kinda show my appreciation i would do a German and Italian Translation of the Mod in the next couple of days.

**Comment by SceptreOfficial** [comment]
@Nilia119 Did you mean to close this? I'm not following your description of the issue. Can you please provide:
- Your RPT log from the session the problem occured
- Steps to reproduce the issue
- If possible, a video of the issue happening

**Comment by Nilia119** [comment]
Yeah, i were kinda retarded and confused two Mods...
Enhanced movement is for me atleast without any bugs...
(I will still do the Translation anyways)
Sorry

**Comment by SceptreOfficial** [comment]
Ok I'll close this issue then. Thanks
