### ISSUE TITLE
acex variable prefix is still being used

### ISSUE THREAD

**Issue by Slatery** [SceptreOfficial/Enhanced-Movement-Rework#22]
Since the merger of ACEX into ACE proper, the acex variable prefix is no longer used, however there is still usage of the prefix in  main's postInit XEH. Not sure what the ramifications would be but it might be the cause of the bug that UEemperor is talking about in the steam comments

**Comment by Drofseh** [comment]
acex prefix is still used for many many things after the merge.

**Comment by SceptreOfficial** [comment]
> acex prefix is still used for many many things after the merge.

Yeah, I thought so too... but just checked ace and the `sittingStatus` variable is using `QGVAR` macro. So guess I need to fix the exit condition.

![image](https://user-images.githubusercontent.com/18005310/156500938-88aff201-d424-4d68-9231-f56cbff9ab61.png)

**Comment by SceptreOfficial** [comment]
Fixed: 9ac3dac1270a160b0985afb66103b65493398cac
I'll push out an update on the workshop soon.

**Comment by SceptreOfficial** [comment]
New release is published.
