### ISSUE TITLE
How to embed EM into a Mission

### ISSUE THREAD

**Issue by Gamer-Dad** [SceptreOfficial/Enhanced-Movement-Rework#23]
Hi Sceptre,
  Apologies for creating a ticket, just had a question. Years ago I recall EM working from within missions and not being "mod" dependent. As awesome as the mod is, I really need it to work from within the mission without CBA. Since you're working on upgrading BadBenson's work I was wondering if you knew if this was possible or not; thanks!

**Comment by SceptreOfficial** [comment]
Sorry for the late response.
This mod is very dependent on CBA and requires config changes so it can't be mission-side only.
