### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by SceptreOfficial** [SceptreOfficial/Enhanced-Movement-Rework#24]
@Nilia119 @Apricot-ale 
I added a few more things related to the new 'assist' feature if you want to try translating them. 😄 
Thanks for the help so far!

**Comment by Nilia119** [comment]
Assist like another Player assisting?

**Comment by SceptreOfficial** [comment]
Yes. A player on a high object can assist a player below if they can't reach it on their own.

**Comment by Apricot-ale** [comment]
Roger that!

**Comment by Nilia119** [comment]
> 

I would start now, as long as you are not allready on it?

**Comment by SceptreOfficial** [comment]
> > 
> 
> I would start now, as long as you are not allready on it?

What do you mean?

**Comment by Nilia119** [comment]
I wanted to avoid conflicts xD

**Comment by SceptreOfficial** [comment]
Oh gotcha

**Comment by SceptreOfficial** [comment]
Resolved conflicts and merged both. Thanks a ton!
fc547295bbd7b027409a73c68fbd2c9cd9566e3b ca6050b9a27a11293ccd03977658152b7f8a1ff7
