### ISSUE TITLE
Add support for double keypress

### ISSUE THREAD

**Issue by mwpowellhtx** [SceptreOfficial/Enhanced-Movement-Rework#28]
For instance, like some vanilla settings, allows for `2xC` keybinds. I would like to bind `2xV` for the _Jump_ scenario, for instance, but it does not seem to be seeing that. Maybe a limitation with `CBA`, I do not know.

**Comment by SceptreOfficial** [comment]
Seems to be a limitation with CBA: https://github.com/CBATeam/CBA_A3/issues/789
Although it seems possible since the last arma update to configure [modded keybinds without CBA](https://community.bistudio.com/wiki/Arma_3:_Modded_Keybinding). I'll look into it later, but pull requests are welcome in the meantime.

**Comment by mwpowellhtx** [comment]
Appreciate you looking into it. Really would like to assign that `2xV`.

Yes, I understand it is a limitation in CBA at the moment, but since it directly affects my ability to get the most out of _EMR_, thought I'd put it on your radar screen at any rate.

**Comment by SceptreOfficial** [comment]
With 09ff58031559bffbc22e11c80062d85986baf6a5 I added vanilla keybinding stuff so `2xV` will be possible. The category is found in the vanilla controls menu. CBA keybinding will still be the default to avoid breaking everyone's settings.

There will probably be confusion between the 2 keybinding menus, but I'm not sure what to do about that right now. CBA should take precedence with the control override thing, so hopefully people figure out and decide to use one or the other... But I bet issues will still be submitted about it.

**Comment by SceptreOfficial** [comment]
Closing since this is resolved in the latest release
