### ISSUE TITLE
Add setting/config property for designating objects as non-climbable

### ISSUE THREAD

**Issue by Freddo3000** [SceptreOfficial/Enhanced-Movement-Rework#3]
Right now unless I'm missing something there is nothing to prevent people from climbing over obstacles such as barbed wire, which should be impassable. Either adding a config property to such objects or adding a setting for it would be a good solution.

These types of objects should not spawn a walkable surface on them either.

**Comment by SceptreOfficial** [comment]
I agree. I'll add blacklisted objects soon. In the meantime, if you need something right away, you can use [EMR_main_fnc_addActionExitCondition](https://github.com/SceptreOfficial/Enhanced-Movement-Rework/blob/master/addons/main/functions/fnc_addActionExitCondition.sqf) and [EMR_main_fnc_addWalkableSurfaceExitCondition](https://github.com/SceptreOfficial/Enhanced-Movement-Rework/blob/master/addons/main/functions/fnc_addWalkableSurfaceExitCondition.sqf) to add additional exit conditions to the climbing/drop action and walkable surface update loop.

**Comment by SceptreOfficial** [comment]
Object class blacklist setting added with: 593de2886fc1de468134b3beab78e365efddcfa3
Update has been pushed to the steam workshop. Closing this issue.

**Comment by Freddo3000** [comment]
Thats the first half of it, would it be possible to have a config property such as 
```sqf
getNumber (configFile >> "CfgVehicles" >> GVARMAIN(canClimb))
```
and
```sqf
getNumber (configFile >> "CfgVehicles" >> GVARMAIN(canWalkOn))
```
?

This would allow it to be set at the addon level.

**Comment by SceptreOfficial** [comment]
I added config level support 87f24a56a845676503a27dc1d8a451f2036268da. The value is `EMR_blacklist = 1`. I didn't separate the blacklist between climbable/walkable surfaces for now. I couldn't think of any situations where you could do one action but not the other. But if you have any ideas, let me know.

**Comment by Freddo3000** [comment]
https://dev.cup-arma3.org/T4194
