### ISSUE TITLE
Multiplayer animation problem

### ISSUE THREAD

**Issue by strutman12345** [SceptreOfficial/Enhanced-Movement-Rework#33]
While playing in a LAN hosted server, myself as host, a player tries to use enhanced movement, but instead of playing the animation, they phase through a wall rather than jump over it. This is visible from both my screen as server host, and his own screen. I am personally able to use the enhanced movement with animations, and the player can see my animations properly.

When checking the settings, all server settings are set to overwrite clients.

Is there any solution to this?

**Comment by SceptreOfficial** [comment]
Are both clients running original EM + EMR? Can you provide RPT logs from both clients?

**Comment by SceptreOfficial** [comment]
As per our conversation via discord, this doesn't seem to be an issue anymore and could possibly have been mod conflict. Either way, it seems resolved.
