### ISSUE TITLE
Climbing without a weapon makes you do the gun on shoulder anim

### ISSUE THREAD

**Issue by MikeTim202** [SceptreOfficial/Enhanced-Movement-Rework#4]
When you try to climb a wall without a gun, as an unarmed character, you do that "putting gun on your shoulder" animation before your character climbs it.
If you climb with binoculars its fine, I think the animation is close enough you should just use that for the unarmed climbing, I don't remember that being a problem with Enhanced Movement before.

**Comment by SceptreOfficial** [comment]
Fixed with afdd5a8ab343f9bb6ab9ff5323deb0d1fa3f488e
