### ISSUE TITLE
Runing a dedicated server on linux. Error -> Server shutdown on start.

### ISSUE THREAD

**Issue by Xagen** [SceptreOfficial/Enhanced-Movement-Rework#5]
When i start the server with this mod loaded, I get an error and it stops the server.

ErrorMessage: Cannot open file '/home/{username}/server/arma3/2034363662\addons\emr_main'
Application terminated intentionally
15:18:21 ../lib/Network/networkServer.cpp ClearNetServer:NOT IMPLEMENTED - briefing!
Cannot open file '/home/{username}/server/arma3/2034363662\addons\emr_main'

Running the server on Ubuntu server OS.

**Comment by SceptreOfficial** [comment]
I don't know how to help. Seems like a linux issue?

**Comment by Xagen** [comment]
It's not a linux issue, Other mods i use work fine.

**Comment by Xagen** [comment]
the only thing i noticed is in the error is.
....\emr_main
while in the addon folder you have
EMR_main.pbo
it might be a naming issue, lower/uppercase issue. Linux sensitive to those kind of errors.

**Comment by SceptreOfficial** [comment]
Did you try just renaming the pbo to lowercase? This issue sounds familiar now that you mentioned that.

**Comment by Xagen** [comment]
I did, it seems to be running. However, I have done this with other mods before, doing this fix can end up breaking the mod. So I'm not sure if this fully fixed it.

**Comment by SceptreOfficial** [comment]
I guess linux is a special animal. I'll change the case where applicable, hopefully it solves the issue onward.

**Comment by SceptreOfficial** [comment]
I've changed case where applicable and changed the final pbo name in the steam release. I'm going to close this issue, if you still have issues after the update, let me know.
