### ISSUE TITLE
Lost on getting controls to work

### ISSUE THREAD

**Issue by SpookOfficial** [SceptreOfficial/Enhanced-Movement-Rework#6]
Sceptre,
Thanks for the work you have done on this. I have been working on my Arma 3 Epoch server for a while now. I have been looking for the best mods I can find. After reviewing, I wanted to give yours a try. I tried the original EM but, if I ran at a wall to vault over it, i was bounced off and damaged. So I looked elsewhere but, then I found your mod.
Currently I have both mods loaded on my client machine, actually ( all of these: @Ryanzombies, CBA_A3, Enhanced Movement,Enhanced Movement Rework,Epoch,JSRS SOUNDMOD,Ladder Tweak 2x).  I also have the same mods of course in the Arma 3 Server directory on that dedicated machine.
When I get in game, To find the settings I have to go to Controls like I am programing my regular keys and then click Configure Addons at the bottom, That is the only place i can see the key settings for the mod.  I left the Shift+V default but set keys for the others. No matter what I do(on the game client) I cannot climb, vault or anything. 
I have been looking but do not see any instructions for what do do on the Arma 3 server.  Do I need to do something there?

**Comment by SceptreOfficial** [comment]
The default key does all the actions depending on the context of your surroundings. You can just leave the default keybind and use that only... unless you want to separate the actions to different keybinds. In that case you should unbind the all-in-one keybind.

Let me know if you have any luck or keep running into problems, otherwise I'll close this issue in a few days if I don't hear back.

**Comment by SpookOfficial** [comment]
Oh wow. There are people out there in the world still! Hah. Thanks for
replying. I have been getting frustrated with not being able to get answers
on different mods and such. So to update you, I also found that from the
main Arma screen (Quick Play, Old Man, Editor screen) I can go to options
there and with i click on Addon Options it does take me into the core
options for the mod. Great.  Enable climbing/dripping and Enable jumping
are "boxed" on. There is a green check by them. Overwrite clients has a
greyed out but "boxed" option.  Overwrite Mission is not 'boxed".  These
are the defaults.

If I hit okay to that and login to my Arma 3 Epoch Server, with the mods
loaded, I can go to ESC > Configure > Controls >Configure Addons. There the
default key for All-in0ne-action is set to Shift+V.   The others were not
set.  In your reply you said I can leave it to the default key.  If I go
back to the game and walk up to a small shack or one of the Hesco boxes and
hold Shift and press V, nothing happens. I look up at the roof and press
again. nothing. If I try and press it while running, he does not hop or
jump or vault.
In my ideal world I would use SPACE to do these actions, if that is
possible. SPACE has always been my jump button. It only makes sense to use
it.  I use a T9 Delux game pad for my PC. It has a more finger friendly
layout over a regular keyboard.
However, I have also tried to program SPACE to the All-in-one key.  I also
removed space from my default Step Over button and from the Use Default
Action button.  Still no go.
I am lost here still. Do I need to do anything on my dedicated server
settigns?

James

**Comment by SceptreOfficial** [comment]
Can you post a screenshot of your addon keybinds and addon options? As well as the .rpt logs from both your client and your server?

https://community.bistudio.com/wiki/Crash_Files

**Comment by SpookOfficial** [comment]
[Spook.zip](https://github.com/SceptreOfficial/Enhanced-Movement-Rework/files/5169355/Spook.zip)
Thank you for taking a look at these.

**Comment by SceptreOfficial** [comment]
The rework isn't running on the server, only on your client... according to the rpt's.

**Comment by SpookOfficial** [comment]
Okay. I missed something in the setup. Are there two different mods? One client and one server version?  I have the "client" version, which subscribed to on Steam and copied it into my A3Server folder.  Do i need to manually download those files from here ?
https://github.com/SceptreOfficial/Enhanced-Movement-Rework

**Comment by SceptreOfficial** [comment]
No, there is only one version. But you're running the original EM on the server without the rework on top of it. Run both on the server, as well as your client. 
The original EM is a dependency for this mod, strictly for the animations. The functions/internal stuff is all replaced with the rework.

**Comment by SpookOfficial** [comment]
Okay> I will check and see why it does not show up

**Comment by SpookOfficial** [comment]
So does it go in the -mod slot or -servermod slot?
-mod="@Epoch;@RyanZombies;@CBA_A3;@Enhanced Movement;@Enhanced Movement Rework" 
-servermod=@EpochHive;@Epoch

**Comment by SceptreOfficial** [comment]
-mod

**Comment by SceptreOfficial** [comment]
Did that fix your issue?

**Comment by SpookOfficial** [comment]
No. But. I will fiddle with oh. Thanks

**Comment by SceptreOfficial** [comment]
This is only happening on your server? Or even in SP?

**Comment by SpookOfficial** [comment]
I have not tried to look for another EM enabled server to try and join so I
have only tested on my own dedicated server

**Comment by SceptreOfficial** [comment]
Since this seems like an isolated issue that's only happening on your end, I'm going to close this issue for now. I can help you out further if you need... just let me know.
